import type {
  CharacterClass,
  Quest,
  QuestDifficulty,
  LootItem,
  ItemSlot,
} from '@grodno/shared';
import { REGISTRY, type ItemTemplate, type QuestTemplate } from '../content/registry.js';

// Static quest templates. Per-character state lives in the character_quests table.
// `state`, `endsAt`, and `availableAt` are populated per-character at list
// time — they're not meaningful on the static template.
export const QUEST_TEMPLATES: readonly Omit<Quest, 'state' | 'endsAt' | 'availableAt'>[] = [
  // ===== AKT I — Szczurogród (L1-5) =====
  {
    id: 'q1',
    title: 'Zebrać grzyby dla wiedźmy',
    desc: 'Staruszka jest głodna. I zła. Jest zgłodniała.',
    icon: 'mushroom',
    diff: 'Łatwe',
    gold: 60,
    xp: 40,
    itemChance: 15,
    duration: 25000,
    requiredLvl: 1,
    chapter: 'akt-1',
  },
  {
    id: 'q2',
    title: 'Przegonić kuny z młyna',
    desc: 'Ugryzły już trzech mieszczan i jednego burmistrza.',
    icon: 'mouse',
    diff: 'Średnie',
    gold: 140,
    xp: 85,
    itemChance: 25,
    duration: 90000,
    requiredLvl: 2,
    chapter: 'akt-1',
  },
  {
    id: 'q3',
    title: 'Rozmowa ze szczurem',
    desc: 'Ponoć gada. Sprawdź. Jeśli gada — pokonaj.',
    icon: 'rat',
    diff: 'Trudne',
    gold: 280,
    xp: 170,
    itemChance: 40,
    duration: 180000,
    requiredLvl: 3,
    chapter: 'akt-1',
  },
  {
    id: 'q4',
    title: 'Najazd na ciasteczarnię',
    desc: 'Złodzieje kradną serniki. Niedopuszczalne.',
    icon: 'cake',
    diff: 'Ekstr.',
    gold: 520,
    xp: 320,
    itemChance: 60,
    duration: 300000,
    requiredLvl: 4,
    chapter: 'akt-1',
  },
  {
    id: 'q5',
    title: 'Kogucik wodza goblinów',
    desc: 'Wódz ukradł koguta burmistrzowi. Koguta odzyskać, wodza... uspokoić.',
    icon: 'crown',
    diff: 'Boss',
    gold: 1100,
    xp: 900,
    itemChance: 100,
    duration: 600000,
    requiredLvl: 5,
    chapter: 'akt-1',
  },
  // ===== AKT II — Las Kunowy (L6-10) =====
  {
    id: 'q6',
    title: 'Pajęczy sabat',
    desc: 'Pająki tańczą w kręgu. Nikt nie wie dlaczego. Przerwij sabat.',
    icon: 'ear',
    diff: 'Łatwe',
    gold: 220,
    xp: 180,
    itemChance: 30,
    duration: 60000,
    requiredLvl: 6,
    chapter: 'akt-2',
  },
  {
    id: 'q7',
    title: 'Mgła nad stawem',
    desc: 'Fioletowa mgła. Ryby mówią po francusku. Zgłoś dyskretnie.',
    icon: 'magic',
    diff: 'Średnie',
    gold: 520,
    xp: 450,
    itemChance: 40,
    duration: 240000,
    requiredLvl: 7,
    chapter: 'akt-2',
  },
  {
    id: 'q8',
    title: 'Kot kowalowej',
    desc: 'Zaginął pręgowany. Kowalowa nie pracuje. Kowal pije. Akcja!',
    icon: 'handshake',
    diff: 'Trudne',
    gold: 960,
    xp: 800,
    itemChance: 50,
    duration: 480000,
    requiredLvl: 8,
    chapter: 'akt-2',
  },
  {
    id: 'q9',
    title: 'Kontrabanda sera',
    desc: 'Ktoś przemyca oscypki za miasto. Oscypki to oscypki, ale skala.',
    icon: 'cheese',
    diff: 'Ekstr.',
    gold: 1800,
    xp: 1500,
    itemChance: 65,
    duration: 900000,
    requiredLvl: 9,
    chapter: 'akt-2',
  },
  {
    id: 'q10',
    title: 'Troll pod mostem',
    desc: 'Pobiera myto niemożliwe do zapłacenia. Płać lub bij. Lepiej bij.',
    icon: 'rock',
    diff: 'Boss',
    gold: 3500,
    xp: 2800,
    itemChance: 100,
    duration: 1500000,
    requiredLvl: 10,
    chapter: 'akt-2',
  },
  // ===== AKT III — Katakumby (L11-15) =====
  {
    id: 'q11',
    title: 'Pieczęć w piwnicy',
    desc: 'Ktoś włamał się do piwnicy katedry. Piwnicy bez piwa. Podejrzane.',
    icon: 'lock',
    diff: 'Łatwe',
    gold: 700,
    xp: 600,
    itemChance: 35,
    duration: 120000,
    requiredLvl: 11,
    chapter: 'akt-3',
  },
  {
    id: 'q12',
    title: 'Kapłan nie wrócił',
    desc: 'Ojciec Tadeusz miał błogosławić sery. Po trzech dniach — cisza.',
    icon: 'scroll',
    diff: 'Średnie',
    gold: 1400,
    xp: 1200,
    itemChance: 45,
    duration: 360000,
    requiredLvl: 12,
    chapter: 'akt-3',
  },
  {
    id: 'q13',
    title: 'Demon woła po imieniu',
    desc: 'Po twoim. Konkretnie po twoim. Zapytaj go po co.',
    icon: 'fire',
    diff: 'Trudne',
    gold: 2800,
    xp: 2400,
    itemChance: 55,
    duration: 720000,
    requiredLvl: 13,
    chapter: 'akt-3',
  },
  {
    id: 'q14',
    title: 'Pustka w lustrze',
    desc: 'Lustro pokazuje coś innego niż ciebie. Coś, co też patrzy.',
    icon: 'orb',
    diff: 'Ekstr.',
    gold: 5000,
    xp: 4500,
    itemChance: 70,
    duration: 1200000,
    requiredLvl: 14,
    chapter: 'akt-3',
  },
  {
    id: 'q15',
    title: 'Tron Hobgoblin Kinga',
    desc: 'Koniec Aktu I. Weźmiesz tron, koronę, i zamkniesz temat rozdziału.',
    icon: 'crown',
    diff: 'Boss',
    gold: 12000,
    xp: 10000,
    itemChance: 100,
    duration: 2400000,
    requiredLvl: 15,
    chapter: 'akt-3',
  },
  // ========== Akt IV — Puszcza Cień (L16-32) ==========
  {
    id: 'q16',
    title: 'Ślady na ścieżce',
    desc: 'Bandyta zostawił odcisk. Kowal chce sprawdzić, na co go stać.',
    icon: 'scroll',
    diff: 'Średnie',
    gold: 900,
    xp: 700,
    itemChance: 30,
    duration: 180000,
    requiredLvl: 16,
    chapter: 'akt-4',
  },
  {
    id: 'q17',
    title: 'Dzik Rzeźnika',
    desc: 'Pod płotem chodzi. Chrapie ciężko. Za mięso będzie złoto.',
    icon: 'sword',
    diff: 'Średnie',
    gold: 1200,
    xp: 900,
    itemChance: 35,
    duration: 240000,
    requiredLvl: 17,
    chapter: 'akt-4',
  },
  {
    id: 'q18',
    title: 'Goblin z luną',
    desc: 'Zwiadowca widziany trzy wsie dalej. Zwiad musi wrócić głuchy.',
    icon: 'dagger',
    diff: 'Trudne',
    gold: 1600,
    xp: 1200,
    itemChance: 40,
    duration: 300000,
    requiredLvl: 18,
    chapter: 'akt-4',
  },
  {
    id: 'q19',
    title: 'Wataha pod wsią',
    desc: 'Wilki zjadły owce. Owczarz dał spokój. Burmistrz — nie.',
    icon: 'mushroom',
    diff: 'Trudne',
    gold: 2000,
    xp: 1500,
    itemChance: 45,
    duration: 420000,
    requiredLvl: 19,
    chapter: 'akt-4',
  },
  {
    id: 'q20',
    title: 'Wilkołak Matecznika',
    desc: 'Boss Szlaków. Zabij — albo wytłumacz rano sąsiadom.',
    icon: 'crown',
    diff: 'Boss',
    gold: 16000,
    xp: 14000,
    itemChance: 100,
    duration: 900000,
    requiredLvl: 20,
    chapter: 'akt-4',
  },
  {
    id: 'q22',
    title: 'Kościsty pasterz',
    desc: 'W kurhanach kroki. Kroki bez nóg. Jeszcze.',
    icon: 'scroll',
    diff: 'Ekstr.',
    gold: 3200,
    xp: 2400,
    itemChance: 50,
    duration: 540000,
    requiredLvl: 22,
    chapter: 'akt-4',
  },
  {
    id: 'q24',
    title: 'Psalm za umarłych',
    desc: 'Szkielet-kapłan odprawia niewłaściwe nabożeństwo. Przerwij.',
    icon: 'orb',
    diff: 'Ekstr.',
    gold: 4200,
    xp: 3200,
    itemChance: 55,
    duration: 660000,
    requiredLvl: 24,
    chapter: 'akt-4',
  },
  {
    id: 'q25',
    title: 'Strzygoń Dziadowski',
    desc: 'Boss Kurhanów. Stara sprawa. Starsza niż twoja babka.',
    icon: 'crown',
    diff: 'Boss',
    gold: 24000,
    xp: 20000,
    itemChance: 100,
    duration: 1200000,
    requiredLvl: 25,
    chapter: 'akt-4',
  },
  {
    id: 'q27',
    title: 'Drzewiec w sercu',
    desc: 'Nie żyw. Nie martw. Stoi. Trzeba coś z tym zrobić.',
    icon: 'mushroom',
    diff: 'Ekstr.',
    gold: 5400,
    xp: 4200,
    itemChance: 60,
    duration: 780000,
    requiredLvl: 27,
    chapter: 'akt-4',
  },
  {
    id: 'q29',
    title: 'Mgła która pamięta',
    desc: 'Widmo mgły szuka kogoś. Nie powinno cię znaleźć.',
    icon: 'orb',
    diff: 'Ekstr.',
    gold: 6800,
    xp: 5400,
    itemChance: 65,
    duration: 900000,
    requiredLvl: 29,
    chapter: 'akt-4',
  },
  {
    id: 'q30',
    title: 'Panna Leszczyna',
    desc: 'Serce Puszczy. Tu las decyduje, kto wróci. Decyduj szybciej.',
    icon: 'crown',
    diff: 'Boss',
    gold: 40000,
    xp: 32000,
    itemChance: 100,
    duration: 1800000,
    requiredLvl: 30,
    chapter: 'akt-4',
  },

  // ============ Akt V — Bagna Czarnej Strzygi (L33-50) ============
  {
    id: 'q31',
    title: 'Chusteczki babci topielczycy',
    desc: 'Zgubiła. Jak zwykle. Tym razem w trzcinach. Wiesz gdzie szukać.',
    icon: 'scroll',
    diff: 'Ekstr.',
    gold: 8500,
    xp: 6500,
    itemChance: 60,
    duration: 900000,
    requiredLvl: 33,
    chapter: 'akt-5',
  },
  {
    id: 'q32',
    title: 'Trzciny na strzechę',
    desc: 'Karczma dziurawa. Trzciny miękkie. Ropuchy nieprzyjemne.',
    icon: 'mushroom',
    diff: 'Ekstr.',
    gold: 11000,
    xp: 8800,
    itemChance: 65,
    duration: 1080000,
    requiredLvl: 36,
    chapter: 'akt-5',
  },
  {
    id: 'q33',
    title: 'Cierniowe mazidło',
    desc: 'Zielarka potrzebuje żywicy z Cierniaków. Pełzających. Żywych.',
    icon: 'mushroom',
    diff: 'Ekstr.',
    gold: 15000,
    xp: 12000,
    itemChance: 70,
    duration: 1320000,
    requiredLvl: 40,
    chapter: 'akt-5',
  },
  {
    id: 'q34',
    title: 'Ołtarzowa woda',
    desc: 'Z czarnego stawu przy ołtarzu. Nie pij. Nie patrz.',
    icon: 'potion',
    diff: 'Ekstr.',
    gold: 22000,
    xp: 18000,
    itemChance: 75,
    duration: 1500000,
    requiredLvl: 45,
    chapter: 'akt-5',
  },
  // Boss quests — q35/q40/q45
  {
    id: 'q35',
    title: 'Zasmucony Topielec Starszy',
    desc: 'Boss Mielizn. Kiedyś ktoś, teraz — wyłącznie mokrość z pretensjami.',
    icon: 'crown',
    diff: 'Boss',
    gold: 55000,
    xp: 44000,
    itemChance: 100,
    duration: 2100000,
    requiredLvl: 35,
    chapter: 'akt-5',
  },
  {
    id: 'q40',
    title: 'Upiór Drwala',
    desc: 'Boss Gąszczu. Rąbał, rąbie, nie przestanie. Przekonaj go.',
    icon: 'crown',
    diff: 'Boss',
    gold: 85000,
    xp: 68000,
    itemChance: 100,
    duration: 2700000,
    requiredLvl: 40,
    chapter: 'akt-5',
  },
  {
    id: 'q45',
    title: 'Czarna Strzyga',
    desc: 'Finał. Altana. Ołtarz. Strzyga. Jedno z nich nie wróci.',
    icon: 'crown',
    diff: 'Boss',
    gold: 160000,
    xp: 130000,
    itemChance: 100,
    duration: 3600000,
    requiredLvl: 47,
    chapter: 'akt-5',
  },
  // ========== AKT VI · GRANIE STRZELISTYCH IGLIC ==========
  // L48-65. 5 questów: 3 normalne + 2 bossy (Q48 mid + Q50 final).
  // Gold/XP +25-40% wzrost vs Q45 (Strzyga). Bossy q48/q50 dropują weapony
  // klasowe legendary (BOSS_UNIQUE_DROPS).
  {
    id: 'q46',
    title: 'Halny po Bagnach',
    desc: 'Wiatr przyniósł kogoś z gór. Albo coś. Sprawdź u Świszcza.',
    icon: 'mushroom',
    diff: 'Trudne',
    gold: 38000,
    xp: 30000,
    itemChance: 60,
    duration: 1800000,
    requiredLvl: 48,
    chapter: 'akt-6',
  },
  {
    id: 'q47',
    title: 'Strażnik na Iglicy',
    desc: 'Pasterze mówią o kamieniu który chodzi. Trudno powiedzieć czy żartują.',
    icon: 'rock',
    diff: 'Ekstr.',
    gold: 55000,
    xp: 44000,
    itemChance: 70,
    duration: 2100000,
    requiredLvl: 50,
    chapter: 'akt-6',
  },
  {
    id: 'q48',
    title: 'Ognista Pani',
    desc: 'Mid-boss. Słyszała że góry są zimne. Postanowiła to naprawić. Sprzeciw się.',
    icon: 'crown',
    diff: 'Boss',
    gold: 120000,
    xp: 96000,
    itemChance: 100,
    duration: 3000000,
    requiredLvl: 52,
    chapter: 'akt-6',
    rewardKeys: 5,
  },
  {
    id: 'q49',
    title: 'Tropy w Lodzie',
    desc: 'Coś tropi was od trzech dni. Zatrzymajcie to, zanim was dopadnie.',
    icon: 'bolt',
    diff: 'Ekstr.',
    gold: 78000,
    xp: 62000,
    itemChance: 75,
    duration: 2700000,
    requiredLvl: 56,
    chapter: 'akt-6',
  },
  {
    id: 'q50',
    title: 'Skarbnik Otchłani',
    desc: 'Final. Sztolnia. Lampka kopalniana. Skarbnik liczy kości. Twoje też.',
    icon: 'crown',
    diff: 'Boss',
    gold: 220000,
    xp: 180000,
    itemChance: 100,
    duration: 3600000,
    requiredLvl: 60,
    chapter: 'akt-6',
    rewardKeys: 5,
  },
];

export interface LootTemplate extends Omit<LootItem, 'id'> {
  slot: ItemSlot;
  atk?: number;
  def?: number;
  mag?: number;
  desc: string;
  /**
   * Classes that can loot this template. Undefined = universal (any class).
   * Weapons are typically restricted: melee (sword/dagger/axe/club) → warrior+rogue;
   * casters (orb/staff) → mage. Armor/potions/trinkets stay universal.
   */
  allowedClasses?: readonly CharacterClass[];
}

const MELEE: readonly CharacterClass[] = ['warrior', 'rogue'];
const CASTER: readonly CharacterClass[] = ['mage'];

export const QUEST_LOOT: Record<QuestDifficulty, readonly LootTemplate[]> = {
  Łatwe: [
    { name: 'Mikstura HP', icon: 'potion-hp-small', rarity: 'common', slot: 'potion', desc: 'Leczy trochę HP.' },
    { name: 'Stary Sztylet', icon: 'dagger-old', rarity: 'common', slot: 'weapon', atk: 3, desc: 'Tępy, ale twój.', allowedClasses: MELEE },
    { name: 'Szmaciany Kapelusz', icon: 'helmet', rarity: 'common', slot: 'head', def: 1, desc: 'Lepszy niż nic.' },
    { name: 'Zgrzebne Rękawice', icon: 'gloves', rarity: 'common', slot: 'hands', def: 1, desc: 'Trochę drapią.' },
    { name: 'Kamyk Szczęścia', icon: 'rock', rarity: 'common', slot: 'any', desc: 'Noś przy sobie. Może zadziała.' },
  ],
  Średnie: [
    { name: 'Żelazny Miecz', icon: 'sword-iron', rarity: 'rare', slot: 'weapon', atk: 8, desc: 'Porządna robota.', allowedClasses: MELEE },
    { name: 'Różdżka Świtu', icon: 'orb', rarity: 'rare', slot: 'weapon', mag: 10, desc: 'Iskrzy przy poranku.', allowedClasses: CASTER },
    { name: 'Skórzany Napierśnik', icon: 'chestplate', rarity: 'rare', slot: 'chest', def: 6, desc: 'Wytrzymały.' },
    { name: 'Mikstura Dużego HP', icon: 'potion-hp-big', rarity: 'rare', slot: 'potion', desc: 'Leczy dużo HP.' },
    { name: 'Obrączka Leśnika', icon: 'ring-woodsman', rarity: 'rare', slot: 'ring', mag: 4, desc: 'Lepiej słyszysz zwierzęta.' },
    { name: 'Hełm Stróża', icon: 'helmet', rarity: 'rare', slot: 'head', def: 8, desc: 'Trzeźwość gwarantowana.' },
  ],
  Trudne: [
    { name: 'Topór Łowcy Szczurów', icon: 'sword', rarity: 'epic', slot: 'weapon', atk: 16, desc: 'Szczury się boją.', allowedClasses: MELEE },
    { name: 'Kostur Echa', icon: 'orb', rarity: 'epic', slot: 'weapon', mag: 18, desc: 'Nigdy nie odpowiada od razu.', allowedClasses: CASTER },
    { name: 'Amulet Gryzonia', icon: 'necklace', rarity: 'epic', slot: 'neck', mag: 8, desc: 'Szeleści w nocy.' },
    { name: 'Pierścień Wymowy', icon: 'ring', rarity: 'epic', slot: 'ring', mag: 6, desc: 'Dodaje charyzmy.' },
    { name: 'Buty Kowalowej', icon: 'boots', rarity: 'epic', slot: 'feet', def: 8, desc: 'Cieple, wygodne, magiczne.' },
    { name: 'Naramiennik Mgły', icon: 'chestplate', rarity: 'epic', slot: 'chest', def: 14, mag: 4, desc: 'Rozpływa się w deszczu.' },
  ],
  'Ekstr.': [
    { name: 'Miecz Serniczarza', icon: 'sword', rarity: 'legendary', slot: 'weapon', atk: 28, desc: 'Pachnie serem.', allowedClasses: MELEE },
    { name: 'Kostur z Pustki', icon: 'orb', rarity: 'legendary', slot: 'weapon', mag: 32, desc: 'Trzyma się sam. Szepcze twoje imię.', allowedClasses: CASTER },
    { name: 'Korona Ciastkowa', icon: 'helmet', rarity: 'legendary', slot: 'head', def: 18, mag: 8, desc: 'Chrupiąca.' },
    { name: 'Pierścień Ojca Tadeusza', icon: 'ring', rarity: 'legendary', slot: 'ring', mag: 16, desc: 'Święty. Trochę tłusty.' },
  ],
  // Boss pool jest fallbackiem; normalnie Q5/Q10/Q15 dropują przez `uniqueDrops`
  // zdefiniowane inline w quest template (patrz `bossUniqueDrops` poniżej).
  Boss: [
    { name: 'Korona Goblina', icon: 'helmet', rarity: 'legendary', slot: 'head', def: 12, mag: 4, desc: 'Cuchnie. Ale błyszczy.' },
    { name: 'Łańcuch Koronny', icon: 'chain-crown', rarity: 'legendary', slot: 'neck', def: 8, mag: 18, desc: 'Z Tronu Hobgoblin Kinga.' },
  ],
};

/**
 * Unique drops for boss quests — class-branched. Guaranteed (questChance 100%),
 * replaces the generic Boss pool roll when present.
 */
export const BOSS_UNIQUE_DROPS: Record<string, Record<CharacterClass, LootTemplate>> = {
  q5: {
    warrior: { name: 'Łup Wodza', icon: 'sword', rarity: 'legendary', slot: 'weapon', atk: 24, desc: 'Z kogucikiem w pochwie.', allowedClasses: MELEE },
    rogue: { name: 'Sztylet Wodza', icon: 'dagger', rarity: 'legendary', slot: 'weapon', atk: 20, desc: 'Cichszy niż kogucik.', allowedClasses: MELEE },
    mage: { name: 'Kostur Wodza', icon: 'orb', rarity: 'legendary', slot: 'weapon', mag: 26, desc: 'Szepcze „kukuryku".', allowedClasses: CASTER },
  },
  q10: {
    warrior: { name: 'Maczuga Trolla', icon: 'sword', rarity: 'legendary', slot: 'weapon', atk: 36, desc: 'Pachnie mostem. I trollem.', allowedClasses: MELEE },
    rogue: { name: 'Sztylet Mglisty', icon: 'dagger-mist-fang', rarity: 'legendary', slot: 'weapon', atk: 30, desc: 'Ostrze zanika, gdy nikt nie patrzy.', allowedClasses: MELEE },
    mage: { name: 'Kosa Trolla', icon: 'orb', rarity: 'legendary', slot: 'weapon', mag: 40, desc: 'Zbiera mgłę ze stawu.', allowedClasses: CASTER },
  },
  q15: {
    warrior: { name: 'Ostrze Tronu', icon: 'sword-throne', rarity: 'legendary', slot: 'weapon', atk: 50, desc: 'Koronne kawałki wciąż w ostrzu.', allowedClasses: MELEE },
    rogue: { name: 'Dwa Sztylety Króla', icon: 'dagger-second', rarity: 'legendary', slot: 'weapon', atk: 42, desc: 'Jeden dla serca, drugi dla korony.', allowedClasses: MELEE },
    mage: { name: 'Berło Hobgoblina', icon: 'scepter-hobgoblin', rarity: 'legendary', slot: 'weapon', mag: 54, desc: 'Mówi głosem pokonanego króla.', allowedClasses: CASTER },
  },
  // Boss quests akt-4 (Chapter 2). Drop'y celowo różne od dungeon-boss drops
  // (które są armor: hands/ring/head). Tu dostajemy dedykowane broń klasowe.
  q20: {
    warrior: { name: 'Kieł Matecznika', icon: 'sword-fang', rarity: 'legendary', slot: 'weapon', atk: 62, desc: 'Wilczy kieł w rękojeści. Gryzie w biegu.', allowedClasses: MELEE },
    rogue: { name: 'Szpony Księżyca', icon: 'claws-moon', rarity: 'legendary', slot: 'weapon', atk: 54, desc: 'Błyszczą przy pełni. Przy nowiu — głodują.', allowedClasses: MELEE },
    mage: { name: 'Kostur Watahy', icon: 'staff-pack', rarity: 'legendary', slot: 'weapon', mag: 68, desc: 'Wyje do księżyca. Niezależnie od pory.', allowedClasses: CASTER },
  },
  q25: {
    warrior: { name: 'Gnat Strzygonia', icon: 'sword-bone', rarity: 'legendary', slot: 'weapon', atk: 78, desc: 'Udowy ojca którego nie znał.', allowedClasses: MELEE },
    rogue: { name: 'Sztylet Kurhanny', icon: 'dagger-kurhan', rarity: 'legendary', slot: 'weapon', atk: 68, desc: 'Tnie bez zadawania pytań.', allowedClasses: MELEE },
    mage: { name: 'Czaszka Lisza', icon: 'skull-lich', rarity: 'legendary', slot: 'weapon', mag: 86, desc: 'Szepcze imiona których nie znasz. Jeszcze.', allowedClasses: CASTER },
  },
  q30: {
    warrior: { name: 'Topór Leszczynny', icon: 'axe-hazel', rarity: 'legendary', slot: 'weapon', atk: 100, desc: 'Drewno rośnie z powrotem. Blade — nie.', allowedClasses: MELEE },
    rogue: { name: 'Szpony Liści', icon: 'claws-leaves', rarity: 'legendary', slot: 'weapon', atk: 88, desc: 'Szeleszczą przed uderzeniem. Nie po.', allowedClasses: MELEE },
    mage: { name: 'Berło Puszczy', icon: 'scepter-forest', rarity: 'legendary', slot: 'weapon', mag: 110, desc: 'Mówi głosem Starszej. Kiedy chce.', allowedClasses: CASTER },
  },
  // Akt V — boss weapons. Drop'y dedykowane, legendary, nie kolidują
  // z dungeon-boss feet drops (R3 dungeon bossy dają buty).
  q35: {
    warrior: { name: 'Kiścień Topielca', icon: 'flail-drowned', rarity: 'legendary', slot: 'weapon', atk: 118, desc: 'Głowa na łańcuchu. Cicho chlupie.', allowedClasses: MELEE },
    rogue: { name: 'Nóż Rybaka', icon: 'knife-fisherman', rarity: 'legendary', slot: 'weapon', atk: 108, desc: 'Rybia łuska w rękojeści. Łap i nie patrz.', allowedClasses: MELEE },
    mage: { name: 'Laska Drifująca', icon: 'staff-drifting', rarity: 'legendary', slot: 'weapon', mag: 132, desc: 'Gałązki wiszą. Same się zaplątują.', allowedClasses: CASTER },
  },
  q40: {
    warrior: { name: 'Topór Nawiedzony', icon: 'axe-haunted', rarity: 'legendary', slot: 'weapon', atk: 148, desc: 'Rąbie sam. Czasem o północy.', allowedClasses: MELEE },
    rogue: { name: 'Siekierka Cieśli', icon: 'hatchet-carpenter', rarity: 'legendary', slot: 'weapon', atk: 134, desc: 'Miała kiedyś właściciela. Ma go nadal.', allowedClasses: MELEE },
    mage: { name: 'Kostur Sękaty', icon: 'staff-forked', rarity: 'legendary', slot: 'weapon', mag: 162, desc: 'Rozwidlony jak droga do piekła.', allowedClasses: CASTER },
  },
  q45: {
    warrior: { name: 'Szabla Strzygi', icon: 'saber-strzyga', rarity: 'legendary', slot: 'weapon', atk: 220, desc: 'Tnie cień. Tnie cisza. Tnie wszystko.', allowedClasses: MELEE },
    rogue: { name: 'Szpony Strzygi', icon: 'claws-strzyga', rarity: 'legendary', slot: 'weapon', atk: 198, desc: 'Cztery ostrza. Cztery grzechy. Wybierz.', allowedClasses: MELEE },
    mage: { name: 'Ossuarium Strzygi', icon: 'staff-ossuary', rarity: 'legendary', slot: 'weapon', mag: 248, desc: 'Czaszka mówi imionami. Słyszysz swoje.', allowedClasses: CASTER },
  },
  // Akt VI — boss weapons. Q48 mid-boss (Ognista Pani), Q50 final (Skarbnik
  // Otchłani). Dropy +10-25% od Q45 baseline. Wszystkie weapony unique-iconified.
  q48: {
    warrior: { name: 'Topór Płomienny', icon: 'axe-flame-lady', rarity: 'legendary', slot: 'weapon', atk: 245, desc: 'Pyta o miarę. Sam ją odmierza.', allowedClasses: MELEE },
    rogue: { name: 'Sztylety Płomienne', icon: 'daggers-flame', rarity: 'legendary', slot: 'weapon', atk: 218, desc: 'Dwa cięcia. Pierwsze rzeźbi, drugie kończy.', allowedClasses: MELEE },
    mage: { name: 'Berło Pani Ognia', icon: 'sceptre-flame-lady', rarity: 'legendary', slot: 'weapon', mag: 275, desc: 'Pamięta każdą iskrę. Każdą zwraca.', allowedClasses: CASTER },
  },
  q50: {
    warrior: { name: 'Topór Halnego Wodza', icon: 'axe-warlord', rarity: 'legendary', slot: 'weapon', atk: 280, desc: 'Tnie wiatr. Wiatr tnie cię w odpowiedzi.', allowedClasses: MELEE },
    rogue: { name: 'Łuk Mroźnej Iglicy', icon: 'bow-frost-spire', rarity: 'legendary', slot: 'weapon', atk: 250, desc: 'Strzela tylko raz. Drugi raz nie potrzeba.', allowedClasses: MELEE },
    mage: { name: 'Berło Skarbnika', icon: 'sceptre-skarbnik', rarity: 'legendary', slot: 'weapon', mag: 320, desc: 'Liczy kości. Twoje też. Cierpliwie.', allowedClasses: CASTER },
  },
};

export function getQuestTemplate(id: string): QuestTemplate | null {
  return REGISTRY.quests.get(id) ?? null;
}

function filterPoolByClass<T extends { allowedClasses?: readonly CharacterClass[] | null }>(
  pool: readonly T[],
  cls: CharacterClass,
): readonly T[] {
  return pool.filter((t) => !t.allowedClasses || t.allowedClasses.includes(cls));
}

/** Roll a quest loot drop for a given difficulty + player class. */
export function rollLoot(
  diff: QuestDifficulty,
  itemChance: number,
  cls: CharacterClass,
): ItemTemplate | null {
  if (Math.random() * 100 >= itemChance) return null;
  const items = REGISTRY.questLoot.get(diff) ?? [];
  const pool = filterPoolByClass(items, cls);
  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}

/** Boss unique drop for a specific quest + class. Returns null if not a boss quest. */
export function getBossUniqueDrop(
  questId: string,
  cls: CharacterClass,
): ItemTemplate | null {
  return REGISTRY.bossDrops.get(questId)?.[cls] ?? null;
}
