export const ICON_NAMES = [
  // Hub / tab bar
  'scroll',
  'sword',
  'dagger',
  'crossed',
  'shop',
  'tavern',
  'gift',
  'castle',
  'helmet',
  'banner',
  // Quests
  'mushroom',
  'mouse',
  'rat',
  'cake',
  // Shop / inventory
  'sword-dawn',
  'helm-hunter',
  'potion',
  'orb',
  'staff-chief',
  'wand-donut',
  'wand-student',
  'wand-shaman',
  'wand-dawn',
  'staff-spy',
  'staff-headless',
  'staff-echo',
  'staff-sabbath',
  'staff-throne',
  'staff-chaos',
  'staff-void',
  'orb-dice',
  'orb-dawn',
  'scepter-void',
  'scepter-throne',
  'scythe-troll',
  // Warrior/rogue weapons (melee unique variants)
  'sword-ghost',
  'sword-iron',
  'sword-cheese',
  'sword-throne',
  'sword-chief',
  'axe-minotaur',
  'axe-headless',
  'axe-throne',
  'axe-ratslayer',
  'mace-troll',
  // Daggers
  'dagger-old',
  'dagger-imp',
  'dagger-slime',
  'dagger-mist',
  'dagger-dragon',
  'dagger-chief',
  // Helmets / crowns / hats
  'helm-old',
  'hat-rag',
  'helm-guard',
  'crown-throne',
  'crown-cake',
  'crown-goblin',
  'crown-undead',
  'crown-obsidian',
  // Chest armor / cloaks
  'cuirass-leather',
  'cuirass-mist',
  'cloak-shadow',
  'cloak-executioner',
  'cloak-shadow-deep',
  // Potions (variants)
  'potion-beet',
  'potion-first',
  'potion-big',
  'potion-warrior',
  'potion-medium',
  // Rings
  'ring-whisper',
  'ring-flight',
  'ring-wraith',
  'ring-wisdom',
  'ring-hobgoblin',
  'ring-father',
  // Necklaces / amulets / chains
  'amulet-rodent',
  'amulet-catacombs',
  'amulet-shaman',
  'chain-crown',
  // Boots
  'boots-spider',
  'boots-smith',
  // Gloves
  'gloves-rough',
  'pill',
  'boots',
  'shield-item',
  'chestplate',
  'gloves',
  'ring',
  'necklace',
  'cheese',
  'rock',
  // UI symbols
  'fire',
  'crown',
  'bolt',
  'spark',
  'arrow-right',
  'lock',
  'check',
  'ear',
  'handshake',
  'dice',
  'megaphone',
  'gold',
  'gem',
  'heart',
  'magic',
  // Stajnie
  'horse',
  'pony',
  'warhorse',
  // --- Chapter 3: Bagna Czarnej Strzygi (tier 6 pool + boss drops) ---
  'sword-hufnal',
  'pipe-reed',
  'chestplate-net',
  'gloves-drowned',
  'ring-mist-oath',
  'potion-black',
  'blade-wraith',
  'staff-runestone',
  'amulet-strzyga',
  'boots-topielec',
  'boots-galoshes',
  'boots-waders',
  'boots-onuce',
  'boots-mossy',
  'boots-clogs',
  'boots-iron-shod',
  'boots-sandals',
  'boots-night-marsh',
  // --- R2 (Puszcza Cień) uniques — rozbite duplikaty ---
  'sword-bor',
  'staff-rune',
  'staff-elder',
  'staff-pack',
  'chestplate-pack',
  'boots-kurhan',
  'boots-bor',
  'ring-forest',
  'dagger-kurhan',
  'claws-leaves',
  'potion-forest',
  'sword-fang',
  'sword-bone',
  'axe-hazel',
  'ring-grave',
  'ring-old-gods',
  'claws-moon',
  'paw-moon',
  'helm-forest',
  'wreath-elder',
  'mask-leaves',
  'scepter-forest',
  // --- R1 / old items — rozbite duplikaty ---
  'ring-woodsman',
  'ring-shadow',
  'ring-signet',
  'shield-peaks',
  'chain-kosciej',
  'bone-finger',
  'skull-mage',
  'skull-lich',
  'scepter-hobgoblin',
  'cuirass-rat',
  'cloak-sewer',
  'cloak-fur',
  'orb-waste',
  'dagger-second',
  'gloves-cloth',
  'gloves-guard',
  'gloves-matecznik',
  'claws-pack',
  'seven-league-boots',
  'chestplate-smith',
  // --- Final dedupe (tier 1 commons vs old quest commons etc.) ---
  'dagger-splinter',
  'sword-rusted',
  'potion-hp-small',
  'potion-hp-big',
  'dagger-mist-fang',
  'amulet-rat-tooth',
  // --- akt-5 boss quest weapons (BOSS_UNIQUE_DROPS q35/q40/q45) ---
  'flail-drowned',
  'knife-fisherman',
  'staff-drifting',
  'axe-haunted',
  'hatchet-carpenter',
  'staff-forked',
  'saber-strzyga',
  'claws-strzyga',
  'staff-ossuary',
  // --- akt-5 shop listings ---
  'potion-marsh',
  'flail-hunter',
  'pipe-shepherd',
  'chestplate-reed',
  'gloves-mud',
  'amulet-mushroom',
  'boots-tar',
  'potion-black-big',
  // --- Guild emblems ---
  'emblem-shield',
  'emblem-tower',
  'emblem-book',
  'emblem-skull',
  // --- Chapter 4: Granie Strzelistych Iglic (tier 7 pool + boss drops) ---
  'axe-frost',
  'staff-spire',
  'cloak-mountain',
  'helm-skarbnik',
  'ring-frost-spire',
  'potion-wind',
  'staff-flame',
  'dagger-spire',
  'amulet-skarbnik',
  // Boss unique drops Q48 (Ognista Pani) — 3 klasy
  'axe-flame-lady',
  'daggers-flame',
  'sceptre-flame-lady',
  // Boss unique drops Q50 (Skarbnik Otchłani) — 3 klasy
  'axe-warlord',
  'bow-frost-spire',
  'sceptre-skarbnik',
  // Shop akt-6
  'potion-altitude',
  'boots-mountain',
  'gloves-shepherd',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
