import type { PaletteKey } from './palettes';
import type { RecipeParts, SkeletonKey } from './skeletons';

export type MonsterTier = 'normal' | 'elite' | 'boss';

export interface MonsterRecipe {
  name: string;
  skeleton: SkeletonKey;
  palette: PaletteKey;
  parts: RecipeParts;
  size?: number;
  tier?: MonsterTier;
}

export const MONSTERS = {
  'goblin-scav': {
    name: 'Goblin Śmieciarz',
    skeleton: 'humanoid',
    palette: 'swamp',
    parts: {
      head: 'goblin',
      ears: 'pointy-long',
      eyes: 'angry-slit',
      mouth: 'fangs',
      body: 'humanoid-lean',
      arms: 'humanoid',
      legs: 'humanoid-short',
      weapon: 'club',
      offhand: 'none',
    },
  },
  'goblin-warrior': {
    name: 'Goblin Wojownik',
    skeleton: 'humanoid',
    palette: 'swamp',
    parts: {
      head: 'goblin',
      ears: 'pointy-long',
      eyes: 'angry-slit',
      mouth: 'snarl',
      body: 'humanoid-lean',
      arms: 'humanoid',
      legs: 'humanoid-short',
      weapon: 'sword',
      offhand: 'shield',
    },
  },
  'kobold-thief': {
    name: 'Kobold Złodziej',
    skeleton: 'humanoid',
    palette: 'forest',
    parts: {
      head: 'goblin',
      ears: 'pointy-short',
      eyes: 'big-round',
      mouth: 'smirk',
      body: 'humanoid-lean',
      arms: 'humanoid',
      legs: 'humanoid-short',
      weapon: 'none',
      offhand: 'torch',
    },
    size: 0.9,
  },
  'troll-cave': {
    name: 'Troll Jaskiniowy',
    skeleton: 'humanoid-big',
    palette: 'stone',
    parts: {
      head: 'round-big',
      ears: 'none',
      eyes: 'angry-slit',
      mouth: 'snarl',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      horns: 'single-spike',
      weapon: 'club',
    },
    size: 1.05,
  },
  'ogre-brute': {
    name: 'Ogr Brutal',
    skeleton: 'humanoid-big',
    palette: 'forest',
    parts: {
      head: 'round-big',
      ears: 'round-small',
      eyes: 'cyclops',
      mouth: 'fangs',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'bone-club',
    },
    size: 1.05,
  },
  minotaur: {
    name: 'Minotaur',
    skeleton: 'humanoid-big',
    palette: 'forest',
    parts: {
      head: 'round-big',
      ears: 'round-small',
      eyes: 'angry-slit',
      mouth: 'snarl',
      horns: 'ram',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'axe',
    },
    size: 1.1,
  },
  'demon-imp': {
    name: 'Imp',
    skeleton: 'flying',
    palette: 'demon',
    parts: {
      head: 'goblin',
      ears: 'bat-wing',
      eyes: 'glowing',
      mouth: 'fangs',
      horns: 'devil',
      body: 'flying',
      wings: 'bat',
      tail: 'devil',
    },
    size: 0.85,
  },
  'bat-dire': {
    name: 'Dire Bat',
    skeleton: 'flying',
    palette: 'shadow',
    parts: {
      head: 'round-big',
      ears: 'bat-wing',
      eyes: 'glowing',
      mouth: 'fangs',
      body: 'flying',
      wings: 'bat',
    },
    size: 0.9,
  },
  'skeleton-soldier': {
    name: 'Szkielet Żołnierz',
    skeleton: 'skeleton',
    palette: 'bone',
    parts: {
      head: 'skull',
      eyes: 'hollow',
      body: 'skeleton-ribs',
      arms: 'bone',
      legs: 'bone',
      weapon: 'sword',
      offhand: 'shield',
    },
  },
  'skeleton-captain': {
    name: 'Szkielet Kapitana',
    skeleton: 'skeleton',
    palette: 'bone',
    parts: {
      head: 'skull',
      eyes: 'glowing',
      body: 'skeleton-ribs',
      arms: 'bone',
      legs: 'bone',
      horns: 'devil',
      weapon: 'axe',
      offhand: 'shield',
    },
    tier: 'elite',
  },
  wraith: {
    name: 'Widmo',
    skeleton: 'skeleton',
    palette: 'undead',
    parts: {
      head: 'skull',
      eyes: 'glowing',
      body: 'skeleton-ribs',
      arms: 'bone',
      legs: 'bone',
      weapon: 'staff',
    },
  },
  'slime-green': {
    name: 'Zielony Slime',
    skeleton: 'blob',
    palette: 'ooze',
    parts: { body: 'blob', eyes: 'big-round', mouth: 'slimy' },
    size: 0.95,
  },
  'slime-shadow': {
    name: 'Mroczny Slime',
    skeleton: 'blob',
    palette: 'shadow',
    parts: { body: 'blob', eyes: 'three', mouth: 'tentacles' },
    tier: 'elite',
  },
  'rat-giant': {
    name: 'Szczur Olbrzym',
    skeleton: 'beast',
    palette: 'rat',
    parts: {
      head: 'rat-snout',
      ears: 'round-small',
      eyes: 'dots',
      body: 'beast-low',
      legs: 'beast-four',
      tail: 'rat',
    },
    size: 0.95,
  },
  'cave-spider': {
    name: 'Jaskiniowy Pająk',
    skeleton: 'beast',
    palette: 'shadow',
    parts: { head: 'insect', eyes: 'compound', body: 'beast-low', legs: 'beast-four' },
    size: 0.9,
  },
  'goblin-shaman': {
    name: 'Goblin Szaman',
    skeleton: 'humanoid',
    palette: 'swamp',
    parts: {
      head: 'goblin',
      ears: 'pointy-long',
      eyes: 'glowing',
      mouth: 'smirk',
      body: 'humanoid-lean',
      arms: 'humanoid',
      legs: 'humanoid-short',
      horns: 'antlers',
      weapon: 'staff',
    },
    tier: 'elite',
  },
  'hobgoblin-king': {
    name: 'Król Hobgoblinów',
    skeleton: 'humanoid-big',
    palette: 'demon',
    parts: {
      head: 'round-big',
      ears: 'pointy-short',
      eyes: 'angry-slit',
      mouth: 'snarl',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      horns: 'devil',
      weapon: 'axe',
      offhand: 'shield',
    },
    tier: 'boss',
    size: 1.15,
  },
  'bone-dragon': {
    name: 'Kościany Smok',
    // Dedykowany skeleton `bone-dragon` — cała sylwetka (czaszka, rogi, szyja,
    // tułów, żebra, skrzydła, ogon, nogi, szpony) narysowana ręcznie w
    // `skeletons.tsx`. Modułowe parts nie pasują do smoczej pozy (humanoid-ish
    // base ignoruje ogon i skrzydła oraz narzuca wyprostowaną postać).
    skeleton: 'bone-dragon',
    palette: 'bone',
    parts: {},
    tier: 'boss',
    size: 1.0,
  },
  'void-horror': {
    name: 'Pustkowy Horror',
    skeleton: 'blob',
    palette: 'void',
    parts: { body: 'blob', eyes: 'three', mouth: 'tentacles' },
    tier: 'boss',
    size: 1.1,
  },
  // Dungeon bossy (Etap 1) — każdy kończy swój loch.
  'rat-king-baltazar': {
    name: 'Szczurzy Król Baltazar',
    skeleton: 'humanoid-big',
    palette: 'rat',
    parts: {
      head: 'round-big',
      ears: 'pointy-short',
      eyes: 'angry-slit',
      mouth: 'snarl',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      horns: 'devil',
      weapon: 'club',
    },
    tier: 'boss',
    size: 1.1,
  },
  'kosciej-elder': {
    name: 'Kosciej Starszy',
    skeleton: 'humanoid',
    palette: 'bone',
    parts: {
      head: 'skull',
      eyes: 'glow',
      mouth: 'teeth-bare',
      body: 'robed',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
    tier: 'boss',
    size: 1.15,
  },
  'lord-of-the-peaks': {
    name: 'Władca Turni',
    skeleton: 'humanoid-big',
    palette: 'stone',
    parts: {
      head: 'round-big',
      horns: 'devil',
      eyes: 'angry-slit',
      mouth: 'snarl',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'axe',
      offhand: 'shield',
    },
    tier: 'boss',
    size: 1.2,
  },
  // ================= CHAPTER 2 · PUSZCZA CIEŃ =================
  // Szlaki Leśne
  'forest-bandit': {
    name: 'Leśny Bandyta',
    skeleton: 'humanoid',
    palette: 'forest',
    parts: {
      head: 'round',
      eyes: 'angry-slit',
      mouth: 'smirk',
      body: 'humanoid',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'dagger',
    },
  },
  'boar-tusk': {
    name: 'Dzik Kłoposty',
    skeleton: 'beast',
    palette: 'forest',
    parts: {
      head: 'rat-snout',
      ears: 'round-small',
      eyes: 'angry-slit',
      mouth: 'fangs',
      body: 'beast-low',
      legs: 'beast-four',
    },
    size: 1.05,
  },
  'goblin-scout': {
    name: 'Zwiadowca Goblinów',
    skeleton: 'humanoid',
    palette: 'swamp',
    parts: {
      head: 'round',
      ears: 'pointy-long',
      eyes: 'angry-slit',
      mouth: 'snarl',
      body: 'humanoid',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'dagger',
    },
  },
  'wolf-pack': {
    name: 'Wilk Watahy',
    skeleton: 'beast',
    palette: 'stone', // szarość wilka; shadow/purple było przerysowane
    parts: {
      head: 'rat-snout',       // najbliższy kształt wilczego pyska
      ears: 'pointy-long',     // wilcze uszy sterczące
      eyes: 'angry-slit',
      mouth: 'fangs',          // kły zamiast dzikiego 'tusks'
      body: 'beast-low',
      legs: 'beast-four',
    },
    size: 1.0,
  },
  'treant-young': {
    name: 'Młody Drzewiec',
    skeleton: 'humanoid-big',
    palette: 'forest',
    parts: {
      head: 'round-big',
      horns: 'antlers',
      eyes: 'glow',
      mouth: 'teeth-bare',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
    },
    size: 1.05,
  },
  // Kurhany Starych Bogów
  'ghoul-risen': {
    name: 'Upiór Wstały',
    skeleton: 'humanoid',
    palette: 'undead',
    parts: {
      head: 'skull',
      eyes: 'glow',
      mouth: 'teeth-bare',
      body: 'humanoid',
      arms: 'thin',
      legs: 'humanoid-tall',
    },
    tier: 'elite',
  },
  'skeleton-priest': {
    name: 'Szkielet Kapłana',
    skeleton: 'humanoid',
    palette: 'bone',
    parts: {
      head: 'skull',
      eyes: 'glow',
      mouth: 'teeth-bare',
      body: 'robed',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
    tier: 'elite',
  },
  'bone-golem': {
    name: 'Kościany Golem',
    skeleton: 'humanoid-big',
    palette: 'bone',
    parts: {
      head: 'skull',
      eyes: 'glow',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
    },
    size: 1.15,
  },
  'wraith-howler': {
    name: 'Widmo Wyjące',
    skeleton: 'blob',
    palette: 'shadow',
    parts: { body: 'blob', eyes: 'glow', mouth: 'teeth-bare' },
    size: 1.0,
  },
  'lich-acolyte': {
    name: 'Adept Lisza',
    skeleton: 'humanoid',
    palette: 'shadow',
    parts: {
      head: 'skull',
      eyes: 'glow',
      mouth: 'snarl',
      body: 'robed',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
    tier: 'elite',
  },
  // Serce Puszczy
  'dryad-matron': {
    name: 'Dziewonia Starsza',
    skeleton: 'humanoid',
    palette: 'forest',
    parts: {
      head: 'round',
      horns: 'antlers',
      eyes: 'glow',
      mouth: 'smirk',
      body: 'robed',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
  },
  'treant-elder': {
    name: 'Drzewiec Pradawny',
    skeleton: 'humanoid-big',
    palette: 'forest',
    parts: {
      head: 'round-big',
      horns: 'antlers',
      eyes: 'angry-slit',
      mouth: 'teeth-bare',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
    },
    tier: 'elite',
    size: 1.2,
  },
  'corrupted-deer': {
    name: 'Skażony Jeleń',
    skeleton: 'beast',
    palette: 'shadow',
    parts: {
      head: 'rat-snout',
      horns: 'antlers',
      ears: 'pointy-long',
      eyes: 'glow',
      mouth: 'fangs',
      body: 'beast-low',
      legs: 'beast-four',
    },
    size: 1.05,
  },
  'mist-wraith': {
    name: 'Widmo Mgły',
    skeleton: 'blob',
    palette: 'frost',
    parts: { body: 'blob', eyes: 'three', mouth: 'tentacles' },
    tier: 'elite',
    size: 1.05,
  },
  'shadow-beast': {
    name: 'Bestia Cienia',
    skeleton: 'beast',
    palette: 'shadow',
    parts: {
      head: 'rat-snout',
      horns: 'devil',
      ears: 'pointy-long',
      eyes: 'glow',
      mouth: 'fangs',
      body: 'beast-low',
      legs: 'beast-four',
    },
    tier: 'elite',
    size: 1.1,
  },
  // Bosse
  'wilkolak-matecznika': {
    name: 'Wilkołak Matecznika',
    skeleton: 'humanoid-big',
    palette: 'shadow',
    parts: {
      head: 'rat-snout',      // wilczy pysk na człowieczym ciele
      ears: 'pointy-long',
      eyes: 'glow',
      mouth: 'fangs',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
    },
    tier: 'boss',
    size: 1.15,
  },
  'strzygon-dziadowski': {
    name: 'Strzygoń Dziadowski',
    skeleton: 'humanoid',
    palette: 'undead',
    parts: {
      head: 'skull',
      eyes: 'glow',
      mouth: 'tusks',
      body: 'robed',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'dagger',
    },
    tier: 'boss',
    size: 1.2,
  },
  'panna-leszczyna': {
    name: 'Panna Leszczyna',
    skeleton: 'humanoid-big',
    palette: 'forest',
    parts: {
      head: 'round',
      horns: 'antlers',
      eyes: 'glow',
      mouth: 'smirk',
      body: 'robed',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
    tier: 'boss',
    size: 1.25,
  },

  // =======================================================
  // Region 3 — Bagna Czarnej Strzygi (akt-5, L33-50, tier 6)
  // =======================================================

  // --- Mielizny Topielców (L33-37) ---
  'topielec-maly': {
    // Mały topielec — blady chłopiec ze stojącej wody, wydrążone oczy.
    name: 'Topielec Mały',
    skeleton: 'humanoid',
    palette: 'undead',
    parts: {
      head: 'goblin',
      eyes: 'hollow',
      mouth: 'slimy',
      body: 'humanoid-lean',
      arms: 'humanoid',
      legs: 'humanoid-short',
    },
    size: 0.88,
  },
  'blotna-pijawka': {
    // Pijawka — bezkształtna pełzająca bryła z ogromnymi zębami.
    name: 'Błotna Pijawka',
    skeleton: 'blob',
    palette: 'ooze',
    parts: {
      body: 'blob',
      eyes: 'three',
      mouth: 'fangs',
    },
    size: 1.0,
  },
  'zabnik-dwukrotny': {
    // Żabnik — dwugłowa ropucha, wyłupiaste oczy.
    name: 'Żabnik Dwukrotny',
    skeleton: 'blob',
    palette: 'swamp',
    parts: {
      body: 'blob',
      eyes: 'three',
      mouth: 'beak',
    },
    size: 1.05,
  },
  'larwa-trzcinowa': {
    // Larwa — owad-larwa siedząca w trzcinie; złożone oczy.
    name: 'Larwa Trzcinowa',
    skeleton: 'flying',
    palette: 'ooze',
    parts: {
      head: 'insect',
      eyes: 'compound',
      mouth: 'tentacles',
      body: 'flying',
      wings: 'insect',
    },
    size: 0.95,
  },
  'mgielny-duch': {
    // Mgielny duch — blada postać unosząca się nad wodą, świecące oczy.
    name: 'Mgielny Duch',
    skeleton: 'flying',
    palette: 'shadow',
    parts: {
      head: 'skull',
      eyes: 'glowing',
      mouth: 'snarl',
      body: 'flying',
      wings: 'none',
    },
    size: 1.0,
  },

  // --- Gąszcz Bolesny (L38-42) ---
  'cierniak-pelzajacy': {
    // Cierniak — nisko pełzające stworzenie z chitynowym pancerzem, owadzi łeb.
    name: 'Cierniak Pełzający',
    skeleton: 'beast',
    palette: 'forest',
    parts: {
      head: 'insect',
      eyes: 'compound',
      body: 'beast-low',
      legs: 'beast-four',
      tail: 'devil',
    },
    size: 1.0,
  },
  'dziadek-z-trzciny': {
    // Dziadek — stary nieboszczyk z brodą, z kosturem w ręku.
    name: 'Dziadek z Trzciny',
    skeleton: 'humanoid',
    palette: 'undead',
    parts: {
      head: 'round-big',
      ears: 'pointy-short',
      eyes: 'hollow',
      mouth: 'grin',
      body: 'humanoid-lean',
      arms: 'humanoid',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
    size: 1.0,
  },
  'kikut-chodzacy': {
    // Kikut — chodzący pień, żadnej broni, potężne ramiona.
    name: 'Kikut Chodzący',
    skeleton: 'humanoid-big',
    palette: 'forest',
    parts: {
      head: 'round-big',
      eyes: 'dots',
      mouth: 'snarl',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
    },
    size: 1.1,
  },
  'ropuch-straznik': {
    // Ropuch — olbrzymia ropucha-strażnik z kłami.
    name: 'Ropuch Strażnik',
    skeleton: 'blob',
    palette: 'swamp',
    parts: {
      body: 'blob',
      eyes: 'big-round',
      mouth: 'fangs',
    },
    size: 1.15,
  },
  'zelazny-komar': {
    // Iron mosquito — insekt z żelaznym rylcem, przezroczyste skrzydła.
    name: 'Żelazny Komar',
    skeleton: 'flying',
    palette: 'frost',
    parts: {
      head: 'insect',
      eyes: 'compound',
      mouth: 'beak',
      body: 'flying',
      wings: 'insect',
    },
    size: 0.95,
  },

  // --- Czarna Obrzędnica (L44-48) ---
  'sluga-strzygi': {
    // Sługa — chudy nieboszczyk, sztylet, kapuzon.
    name: 'Sługa Strzygi',
    skeleton: 'humanoid',
    palette: 'shadow',
    parts: {
      head: 'skull',
      eyes: 'glowing',
      mouth: 'fangs',
      body: 'humanoid-lean',
      arms: 'humanoid',
      legs: 'humanoid-tall',
      weapon: 'sword',
    },
    size: 1.0,
  },
  'nietoperz-upiora': {
    // Upiorny nietoperz — wielkie skrzydła, świecące oczy.
    name: 'Nietoperz Upiora',
    skeleton: 'flying',
    palette: 'shadow',
    parts: {
      head: 'goblin',
      ears: 'bat-wing',
      eyes: 'glowing',
      mouth: 'fangs',
      body: 'flying',
      wings: 'bat',
    },
    size: 1.05,
  },
  'slepy-oracz': {
    // Ślepy Oracz — zombie chłop z kijem/widłami.
    name: 'Ślepy Oracz',
    skeleton: 'humanoid',
    palette: 'undead',
    parts: {
      head: 'round-big',
      eyes: 'hollow',
      mouth: 'grin',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
    size: 1.05,
  },
  'kocica-obrzedowa': {
    // Ritualistyczna kocica — czterech-łapa bestia z świecącymi oczyma.
    name: 'Kocica Obrzędowa',
    skeleton: 'beast',
    palette: 'shadow',
    parts: {
      head: 'rat-snout',
      eyes: 'glowing',
      body: 'beast-low',
      legs: 'beast-four',
      tail: 'devil',
    },
    size: 1.0,
  },
  'pan-ogrodow': {
    // Pan Ogrodów — wysoki mag-pan, kapuzon, kostur, pustka w oczodołach.
    name: 'Pan Ogrodów Sczeźnienia',
    skeleton: 'humanoid-big',
    palette: 'void',
    parts: {
      head: 'skull',
      horns: 'devil',
      eyes: 'glowing',
      mouth: 'fangs',
      body: 'humanoid-bulk',
      arms: 'thin',
      legs: 'humanoid-tall',
      weapon: 'staff',
    },
    tier: 'elite',
    size: 1.15,
  },

  // --- Region 3 bossy ---
  'zasmucony-topielec-starszy': {
    // Zasmucony Topielec Starszy — potężny topielec z morderczą aurą.
    name: 'Zasmucony Topielec Starszy',
    skeleton: 'humanoid-big',
    palette: 'undead',
    parts: {
      head: 'round-big',
      eyes: 'hollow',
      mouth: 'slimy',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'claws',
    },
    tier: 'boss',
    size: 1.2,
  },
  'upior-drwala': {
    // Upiór Drwala — duch drwala z wielkim toporem, świecące oczy.
    name: 'Upiór Drwala',
    skeleton: 'humanoid-big',
    palette: 'shadow',
    parts: {
      head: 'round-big',
      eyes: 'glowing',
      mouth: 'snarl',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'axe',
    },
    tier: 'boss',
    size: 1.22,
  },
  'czarna-strzyga': {
    // Czarna Strzyga — wampirka z dwoma duszami, skrzydła nietoperza, kły.
    name: 'Czarna Strzyga',
    skeleton: 'humanoid-big',
    palette: 'void',
    parts: {
      head: 'skull',
      horns: 'single-spike',
      ears: 'bat-wing',
      eyes: 'glowing',
      mouth: 'fangs',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'claws',
      wings: 'bat',
    },
    tier: 'boss',
    size: 1.3,
  },
  // ========== AKT VI — Granie Strzelistych Iglic (tier 7) ==========
  // Wszystkie używają istniejących parts/palet — frost dla halnego klimatu,
  // stone dla skał, demon dla Ognistej Pani, void dla Skarbnika.
  'swiszcz-hardy': {
    // Świszcz Hardy — świstak-mutant z gór, agresywny po halnym.
    name: 'Świszcz Hardy',
    skeleton: 'beast',
    palette: 'rat',
    parts: {
      head: 'rat-snout',
      ears: 'round-small',
      eyes: 'angry-slit',
      mouth: 'fangs',
      body: 'beast-low',
      arms: 'humanoid',
      legs: 'beast-four',
      tail: 'rat',
    },
    size: 0.95,
  },
  'straznik-granii': {
    // Strażnik Granii — kamienny golem ze szczytów, oczy żarzą się na lawowo.
    name: 'Strażnik Granii',
    skeleton: 'humanoid-big',
    palette: 'stone',
    parts: {
      head: 'round-big',
      horns: 'single-spike',
      eyes: 'glowing',
      mouth: 'none',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'club',
    },
    size: 1.15,
  },
  'lodowy-tropiciel': {
    // Lodowy Tropiciel — wilkozjawa, lód zamiast futra, ślad nigdy nie znika.
    name: 'Lodowy Tropiciel',
    skeleton: 'beast',
    palette: 'frost',
    parts: {
      head: 'round-big',
      ears: 'pointy-long',
      eyes: 'glowing',
      mouth: 'fangs',
      body: 'beast-low',
      arms: 'none',
      legs: 'beast-four',
      tail: 'devil',
    },
    size: 1.0,
  },
  'mrozny-upior': {
    // Mroźny Upior — duch zamarzniętego pasterza halnego, świeci się błękitnie.
    name: 'Mroźny Upior',
    skeleton: 'skeleton',
    palette: 'frost',
    parts: {
      head: 'skull',
      eyes: 'glowing',
      mouth: 'fangs',
      body: 'skeleton-ribs',
      arms: 'bone',
      legs: 'bone',
      weapon: 'staff',
    },
    tier: 'elite',
    size: 1.05,
  },
  'ognista-pani': {
    // Ognista Pani — boss mid-akt-6. Płomienna zjawa ze szczytu, latająca,
    // z rogami diabła. Słyszała że góry są zimne. Postanowiła to naprawić.
    name: 'Ognista Pani',
    skeleton: 'flying',
    palette: 'demon',
    parts: {
      head: 'round-big',
      horns: 'devil',
      eyes: 'glowing',
      mouth: 'snarl',
      wings: 'dragon',
      weapon: 'staff',
    },
    tier: 'boss',
    size: 1.2,
  },
  'skarbnik-otchlani': {
    // Skarbnik Otchłani — finalny boss akt-6. Duch górnika strzegący skarbu,
    // szkieletowa głowa z porożem, w garści topór i pochodnia. Skarb to twoje kości.
    name: 'Skarbnik Otchłani',
    skeleton: 'humanoid-big',
    palette: 'void',
    parts: {
      head: 'skull',
      horns: 'antlers',
      eyes: 'glowing',
      mouth: 'tentacles',
      body: 'humanoid-bulk',
      arms: 'bulky',
      legs: 'humanoid-tall',
      weapon: 'axe',
      offhand: 'torch',
    },
    tier: 'boss',
    size: 1.25,
  },
} as const satisfies Record<string, MonsterRecipe>;

export type MonsterSlug = keyof typeof MONSTERS;

export function monsterBySlug(slug: string): MonsterRecipe {
  return (MONSTERS as Record<string, MonsterRecipe>)[slug] ?? MONSTERS['goblin-scav'];
}
